// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FabricaDB.Migrations
{
    [DbContext(typeof(FabricaContext))]
    partial class FabricaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fabrica.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("País")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Fabrica.Models.PedidoxTela", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("TelaId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PedidoId");

                    b.HasIndex("TelaId");

                    b.ToTable("PedidoxTela");
                });

            modelBuilder.Entity("Fabrica.Models.Tela", b =>
                {
                    b.Property<int>("TelaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Metros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TelaId");

                    b.ToTable("Tela");
                });

            modelBuilder.Entity("Fabrica.Models.PedidoxTela", b =>
                {
                    b.HasOne("Fabrica.Models.Pedido", "Pedido")
                        .WithMany("LineasPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fabrica.Models.Tela", "Tela")
                        .WithMany("LineasTela")
                        .HasForeignKey("TelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Tela");
                });

            modelBuilder.Entity("Fabrica.Models.Pedido", b =>
                {
                    b.Navigation("LineasPedido");
                });

            modelBuilder.Entity("Fabrica.Models.Tela", b =>
                {
                    b.Navigation("LineasTela");
                });
#pragma warning restore 612, 618
        }
    }
}
